### PR TITLE
Add Organizers page

### PR DESCRIPTION
**Pull request by toshi835**
Added Organizers tab and page.

Result: 
organizers

### CODE REVIEW

**Comment by toshi835** [comment]
This closes #7.

**Comment by toshi835** [comment]
Ask ishigaki-san for the confirmation such as order of members and our role name.

**Comment by toshi835** [comment]
Addressed ishigaki-san's feedback below
- change niwa-san's role and order
- split pc chairs and local organizers

Then updated screenshot above.

**Comment by takatoy** [comment]
Updated design to match other pages.
How do you think? @toshi835 
127 0 0 1_8888_organizers html

**Comment by toshi835** [comment]
Thanks a lot! looks perfect. 

(personal note)
- use `rem`, not `px`
- color of cards are white (default)
- using inline style if the style will not be re-used
- use common header-like components such as tokyo photo in base.html

**Comment by toshi835** [comment]
[nit] I know there are un-used css components but we can remove them whenever we wanna do refactor.

**Pull request merged**
